bottle:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224

cable:
  backbone: wideresnet101
  layer: layer3
  resize: 336
  imagesize: 320

capsule:
  backbone: wideresnet101
  layer: layer3
  resize: 324
  imagesize: 320

carpet:
  backbone: wideresnet101
  layer: layer3
  resize: 336
  imagesize: 320

grid:
  backbone: wideresnet101
  layer: layer2
  resize: 320
  imagesize: 320

hazelnut:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224

leather:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224

metal_nut:
  backbone: wideresnet101
  layer: layer2
  resize: 224
  imagesize: 224

pill:
  backbone: wideresnet101
  layer: layer2
  resize: 284
  imagesize: 280

screw:
  backbone: wideresnet101
  layer: layer2
  resize: 368
  imagesize: 320

tile:
  backbone: wideresnet101
  layer: layer2
  resize: 332
  imagesize: 320

toothbrush:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224

transistor:
  backbone: wideresnet101
  layer: layer3
  resize: 336
  imagesize: 320

wood:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224

zipper:
  backbone: wideresnet101
  layer: layer2
  resize: 256
  imagesize: 224
