FROM python:3.7.2
RUN pip install --upgrade pip
RUN pip install cryptography==3.4.7 numpy==1.19.1 elasticsearch==7.12.0 objsize==0.3.3 psycopg2==2.9.2 flask==2.1.0 flask-Cors==3.0.10 flask-RESTful==0.3.9
